mod action_dispatcher;
pub(crate) mod brush;
mod brush_sync;
pub(crate) mod controls;
pub(crate) mod cursor;
pub(crate) mod dialogs;
mod editor;
pub(crate) mod editor_base;
mod editor_slot;
pub(crate) mod field;
mod field_session;
pub(crate) mod fields;
mod input;
mod manager;
mod modal_stack;
pub(crate) mod registry;
pub(crate) mod runtime;
mod view;

pub(crate) use manager::PanelManager;
