name: Launcher

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            os: "linux"
            arch: "--x64"

          - runner: windows-latest
            os: "win"
            arch: "--x64"

    steps:
      - uses: actions/checkout@v2
        with:
          # This should fix git rev-list --count HEAD
          # https://stackoverflow.com/a/65056108
          fetch-depth: 0
          path: repo-folder

      - uses: actions/checkout@v2
        with:
          repository: gajop/spring-launcher
          path: spring-launcher

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Prepare folder structure
        run: |
          mkdir build
          cp spring-launcher/* -r build/
          cp repo-folder/dist_cfg/* -r build/src/
          mkdir -p build/{bin,files,build}
          [ -d build/src/bin/ ] && mv build/src/bin/* build/bin/
          [ -d build/src/files/ ] && mv build/src/files/* build/files/
          [ -d build/src/build/ ] && mv build/src/build/* build/build/
          rm -rf build/src/{bin,files,build}

          find build/

          exit 0

      - name: Set package version
        id: PACKAGE_VERSION
        run: |
          cd repo-folder
          echo "version=1.$(git rev-list --count HEAD).0" >> "$GITHUB_OUTPUT"

      - name: Make package.json
        run: |
          echo "Making build for version: ${{ steps.PACKAGE_VERSION.outputs.version }}"
          node ./repo-folder/build/make_package_json.js build/package.json repo-folder/dist_cfg/config.json ${{ github.repository }} ${{ steps.PACKAGE_VERSION.outputs.version }}

          cat build/package.json

      - name: Build
        run: |
          cd build
          npm install
          npm run build-${{ matrix.os }} -- ${{ matrix.arch }} --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Clean up unwanted build artifacts
        run: |
          rm -f build/dist/builder-debug.yml
          rm -rf build/dist/linux-unpacked
          rm -rf build/dist/win-unpacked

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpringBoard-${{ matrix.os }}-${{ steps.PACKAGE_VERSION.outputs.version }}
          path: build/dist/**/*